name: Force Deploy Mobile Updates

on:
  workflow_dispatch:

jobs:
  force-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Clean and build
      run: |
        rm -rf dist
        npx vite build --config vite.config.pages.ts

    - name: Copy data and add cache busting
      run: |
        cp -r data dist/
        # Add unique timestamp to force cache refresh
        TIMESTAMP=$(date +%s)
        sed -i "s/<\/head>/<!-- Cache-bust: $TIMESTAMP --><\/head>/" dist/index.html

    - name: Delete existing gh-pages branch
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git push origin --delete gh-pages || echo "gh-pages branch doesn't exist"

    - name: Deploy fresh content
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
        force_orphan: true
        enable_jekyll: false
        cname: aiglossary.techfunhouse.com
        commit_message: 'Force deploy mobile responsive updates'