name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npx vite build --config vite.config.pages.ts

    - name: Prepare GitHub Pages deployment
      run: |
        # Copy built files to root for GitHub Pages
        cp dist/index.html .
        cp -r dist/assets .
        
        # Ensure data files are available at root level
        cp -r data dist/
        
        # Create .nojekyll to prevent Jekyll processing
        touch .nojekyll

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        exclude_assets: |
          node_modules/**
          server/**
          client/src/**
          .github/**
          *.ts
          *.json
          !data/*.json
          !package.json